apiVersion: v1
kind: Service
metadata:
  name: goldmane-ext
  namespace: calico-system
spec:
  ports:
  - port: 7443
    protocol: TCP
    targetPort: 7443
  selector:
    k8s-app: goldmane
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
